name: create_release_test

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  create_release:
    name: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v0.1
          name: CreateReleaseTest v0.1
          body_path: ChangeTest.md
          generate_release_notes: true
      - name: upload assets
        id: upload_assets
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v0.1
          files: README.md