name: diff check test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: diff-check
        id: diff
        uses: k-shinn/file-diff@url_echo_test
        with:
          target: 'CreateTest.md'
      - name: result
        run: echo "${{ steps.diff.outputs.isChanged }}"
